//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeTorneo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attributi()
        {
            this.Personaggi = new HashSet<Personaggi>();
        }
    
        public int idAttributo { get; set; }
        public Nullable<int> Forza { get; set; }
        public Nullable<int> Difesa { get; set; }
        public Nullable<int> Armatura { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> PExpt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personaggi> Personaggi { get; set; }
    }
}
