//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeTorneo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iscrizioni
    {
        public int idIscrizione { get; set; }
        public Nullable<int> fkTorneo { get; set; }
        public Nullable<int> fkUtente { get; set; }
    
        public virtual Tornei Tornei { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
