//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeTorneo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tornei
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tornei()
        {
            this.Iscrizioni = new HashSet<Iscrizioni>();
        }
    
        public int idTorneo { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Durata { get; set; }
        public Nullable<int> Num_Max { get; set; }
        public string Regolamento { get; set; }
        public Nullable<int> Premio { get; set; }
        public string Descrizione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iscrizioni> Iscrizioni { get; set; }
    }
}
